import AppKit
import Testing
import CreativeNotchCore
@testable import CreativeNotchUI

/// Converting an `NSPasteboard` into something the ring will accept.
///
/// A named pasteboard is used rather than the general one so the tests
/// cannot disturb the machine's actual clipboard.
///
/// This is the security boundary of the module: the skip-type check runs
/// before any content is read, so a password manager's entry is never
/// materialised at all.
@MainActor
struct PasteboardClipboardTests {

    private func makePasteboard() -> NSPasteboard {
        let pb = NSPasteboard(name: NSPasteboard.Name("CreativeNotchClipTest-\(UUID().uuidString)"))
        pb.clearContents()
        return pb
    }

    private func pngData() -> Data {
        let image = NSImage(size: NSSize(width: 4, height: 4))
        image.lockFocus()
        NSColor.red.setFill()
        NSRect(x: 0, y: 0, width: 4, height: 4).fill()
        image.unlockFocus()

        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:])
        else { return Data() }
        return png
    }

    // MARK: - The skip types

    /// The convention password managers use. Most clipboard managers
    /// ignore it and quietly write passwords to disk; this one is the
    /// reason the module exists in the shape it does.
    @Test func concealedContentIsNeverCaptured() {
        let pb = makePasteboard()
        pb.setString("hunter2", forType: .nsConcealed)
        pb.setString("hunter2", forType: .string)

        #expect(pb.clipboardCapture() == nil)
    }

    @Test func transientContentIsNeverCaptured() {
        let pb = makePasteboard()
        pb.setString("temporary", forType: .nsTransient)
        pb.setString("temporary", forType: .string)

        #expect(pb.clipboardCapture() == nil)
    }

    @Test func autoGeneratedContentIsNeverCaptured() {
        let pb = makePasteboard()
        pb.setString("generated", forType: .nsAutoGenerated)
        pb.setString("generated", forType: .string)

        #expect(pb.clipboardCapture() == nil)
    }

    @Test func theSkipTypesUseTheConventionalIdentifiers() {
        #expect(NSPasteboard.PasteboardType.nsConcealed.rawValue == "org.nspasteboard.ConcealedType")
        #expect(NSPasteboard.PasteboardType.nsTransient.rawValue == "org.nspasteboard.TransientType")
        #expect(NSPasteboard.PasteboardType.nsAutoGenerated.rawValue == "org.nspasteboard.AutoGeneratedType")
    }

    /// A concealed marker suppresses an *image* too. Checking only the
    /// string path would leave a copied secret screenshot captured.
    @Test func concealedSuppressesImagesAsWell() {
        let pb = makePasteboard()
        pb.setData(pngData(), forType: .png)
        pb.setString("", forType: .nsConcealed)

        #expect(pb.clipboardCapture() == nil)
    }

    // MARK: - Text

    @Test func plainTextIsCaptured() {
        let pb = makePasteboard()
        pb.setString("hello there", forType: .string)

        #expect(pb.clipboardCapture() == .text("hello there"))
    }

    @Test func whitespaceOnlyTextIsIgnored() {
        let pb = makePasteboard()
        pb.setString("   \n  ", forType: .string)

        #expect(pb.clipboardCapture() == nil)
    }

    @Test func anEmptyPasteboardYieldsNothing() {
        #expect(makePasteboard().clipboardCapture() == nil)
    }

    /// Over-cap text is skipped outright rather than truncated: a
    /// half-written string pastes back as corrupt data.
    @Test func overSizedTextIsSkippedNotTruncated() {
        let pb = makePasteboard()
        pb.setString(String(repeating: "a", count: ClipboardLimits.maxTextBytes + 1), forType: .string)

        #expect(pb.clipboardCapture() == nil)
    }

    // MARK: - Images

    @Test func pngDataIsCaptured() throws {
        let pb = makePasteboard()
        let data = pngData()
        pb.setData(data, forType: .png)

        #expect(pb.clipboardCapture() == .image(data, ext: "png"))
    }

    /// macOS screenshots reach the pasteboard as TIFF, and `NSPasteboard`
    /// TIFF is **uncompressed** — roughly `width × height × 4` bytes. A
    /// 14" MacBook Pro full-screen grab is about 24 MB that way, which
    /// would blow straight through the 10 MB cap and be silently dropped.
    /// The same image as PNG is a couple of megabytes.
    ///
    /// So TIFF is re-encoded before the cap is applied, and what lands in
    /// the ring is always PNG.
    @Test func tiffIsTranscodedToPNG() throws {
        let pb = makePasteboard()
        let image = NSImage(size: NSSize(width: 8, height: 8))
        image.lockFocus()
        NSColor.blue.setFill()
        NSRect(x: 0, y: 0, width: 8, height: 8).fill()
        image.unlockFocus()
        let tiff = try #require(image.tiffRepresentation)
        pb.setData(tiff, forType: .tiff)

        let captured = try #require(pb.clipboardCapture())
        guard case .image(let data, let ext) = captured else {
            Issue.record("expected an image")
            return
        }

        #expect(ext == "png")
        #expect(data != tiff)
        // A PNG signature, so this is genuinely re-encoded rather than
        // TIFF bytes relabelled.
        #expect(data.prefix(8) == Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]))
    }

    /// The point of transcoding: a large flat image is far over the cap as
    /// TIFF and comfortably under it as PNG. Judged after re-encoding, it
    /// is kept — judged before, it would have been thrown away.
    @Test func aLargeScreenshotSurvivesBecauseItIsTranscoded() throws {
        // 1600×1600 × 4 bytes ≈ 10.2 MB of TIFF, just over the cap.
        let image = NSImage(size: NSSize(width: 1600, height: 1600))
        image.lockFocus()
        NSColor.white.setFill()
        NSRect(x: 0, y: 0, width: 1600, height: 1600).fill()
        image.unlockFocus()

        let tiff = try #require(image.tiffRepresentation)
        #expect(tiff.count > ClipboardLimits.maxImageBytes)

        let pb = makePasteboard()
        pb.setData(tiff, forType: .tiff)

        let captured = try #require(pb.clipboardCapture())
        #expect(captured.byteCount < ClipboardLimits.maxImageBytes)
    }

    /// PNG already on the pasteboard is taken as-is. Re-encoding it would
    /// cost time and gain nothing.
    @Test func existingPNGIsNotReEncoded() {
        let pb = makePasteboard()
        let data = pngData()
        pb.setData(data, forType: .png)
        pb.setData(Data([0x4D, 0x4D]), forType: .tiff)

        #expect(pb.clipboardCapture() == .image(data, ext: "png"))
    }

    /// Undecodable bytes claiming to be TIFF must yield nothing rather
    /// than crashing or storing garbage.
    @Test func unreadableImageDataIsIgnored() {
        let pb = makePasteboard()
        pb.setData(Data([0x00, 0x01, 0x02, 0x03]), forType: .tiff)

        #expect(pb.clipboardCapture() == nil)
    }

    @Test func overSizedImagesAreSkipped() {
        let pb = makePasteboard()
        pb.setData(Data(repeating: 0, count: ClipboardLimits.maxImageBytes + 1), forType: .png)

        #expect(pb.clipboardCapture() == nil)
    }

    // MARK: - File URLs

    /// Copying a file in Finder puts its path on the pasteboard as a
    /// string too. Capturing that would fill the clipboard history with
    /// paths for something the shelf already handles properly — by
    /// copying the file, so the entry survives the original moving.
    @Test func copiedFilesAreLeftToTheShelf() {
        let pb = makePasteboard()
        pb.writeObjects([URL(fileURLWithPath: "/tmp/thing.pdf") as NSURL])
        pb.setString("/tmp/thing.pdf", forType: .string)

        #expect(pb.clipboardCapture() == nil)
    }

    // MARK: - Writing back

    /// Clicking an entry writes it back and nothing more. No synthesized
    /// paste keystroke: spec section 6 commits this module to needing no
    /// permission, and key synthesis would require Accessibility.
    @Test func writingTextBackRoundTrips() {
        let pb = makePasteboard()
        pb.write(.text("round trip"))

        #expect(pb.string(forType: .string) == "round trip")
        #expect(pb.clipboardCapture() == .text("round trip"))
    }

    @Test func writingAnImageBackRoundTrips() {
        let pb = makePasteboard()
        let data = pngData()
        pb.write(.image(data, ext: "png"))

        #expect(pb.data(forType: .png) == data)
        #expect(pb.clipboardCapture() == .image(data, ext: "png"))
    }

    /// Writing clears what was there first, so a write cannot leave the
    /// previous entry's types alongside the new one — which would make the
    /// next capture return the wrong thing.
    @Test func writingReplacesTheWholePasteboard() {
        let pb = makePasteboard()
        pb.setString("old", forType: .string)
        pb.write(.image(pngData(), ext: "png"))

        #expect(pb.string(forType: .string) == nil)
    }
}
