import AppKit
import CreativeNotchCore

public extension NSPasteboard.PasteboardType {

    /// The convention password managers use to say "do not record this".
    /// Most clipboard managers ignore it and quietly write passwords to
    /// disk; honouring it is half of why this module exists.
    static let nsConcealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    /// Content that is on the pasteboard only in passing.
    static let nsTransient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    /// Content an app put there on the user's behalf rather than because
    /// they asked for it.
    static let nsAutoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

public extension NSPasteboard {

    /// Every type this module refuses to look at.
    static let skippedTypes: [NSPasteboard.PasteboardType] = [
        .nsConcealed, .nsTransient, .nsAutoGenerated
    ]

    /// What this pasteboard offers the clipboard ring, with AppKit
    /// stripped away — or `nil` if it offers nothing worth keeping.
    ///
    /// The order is the security order:
    ///
    /// 1. **Skip types first**, before a single byte of content is read.
    ///    A password manager's entry is never materialised at all, which
    ///    is a stronger guarantee than reading it and discarding it.
    /// 2. **File URLs** mean the shelf's job, not this one. Copying a file
    ///    in Finder also puts its path on as a string, and capturing that
    ///    would fill the history with paths for something the shelf
    ///    already handles properly — by copying the file, so the entry
    ///    survives the original moving.
    /// 3. **Images before text**, because an image and its alt text are
    ///    often both present and the image is what was copied.
    ///
    /// Images are always stored as PNG. `NSPasteboard` TIFF is
    /// uncompressed — roughly `width × height × 4` bytes, so a 14"
    /// MacBook Pro screenshot arrives at about 24 MB. Judged at that size
    /// it would fail the 10 MB cap and be silently dropped, which is the
    /// wrong answer for the single most common thing this app will be
    /// asked to remember. Re-encoded first, the same image is a couple of
    /// megabytes and is kept.
    ///
    /// The cap is therefore applied to what the ring will actually hold,
    /// not to what the pasteboard happened to hand over.
    func clipboardCapture() -> ClipboardContent? {
        let available = types ?? []
        guard !available.contains(where: { Self.skippedTypes.contains($0) }) else { return nil }

        if let urls = readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           !urls.isEmpty {
            return nil
        }

        // PNG already on the pasteboard is taken as-is: re-encoding it
        // would cost time and gain nothing.
        if let png = data(forType: .png) {
            let content = ClipboardContent.image(png, ext: "png")
            return ClipboardLimits.accepts(content) ? content : nil
        }

        if let tiff = data(forType: .tiff) {
            guard let png = Self.pngData(fromTIFF: tiff) else { return nil }
            let content = ClipboardContent.image(png, ext: "png")
            return ClipboardLimits.accepts(content) ? content : nil
        }

        if let text = string(forType: .string) {
            let content = ClipboardContent.text(text)
            return ClipboardLimits.accepts(content) ? content : nil
        }

        return nil
    }

    /// Re-encodes uncompressed pasteboard TIFF as PNG.
    ///
    /// Runs on the main actor, where a large image costs on the order of
    /// 50–150 ms. That is acceptable because image copies are rare — a
    /// few a minute at the very most — but it is the thread driving the
    /// notch animation, so if it ever hitches visibly this is the thing to
    /// move off it. Measure before assuming it does.
    ///
    /// Returns `nil` for bytes that do not decode, so undecodable data
    /// yields no entry rather than a garbage one.
    static func pngData(fromTIFF tiff: Data) -> Data? {
        guard let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    /// Puts an entry back on the pasteboard, and does nothing else.
    ///
    /// No synthesized paste keystroke: spec section 6 commits this module
    /// to needing no permission, and key synthesis would require
    /// Accessibility. The user pastes it themselves.
    ///
    /// `clearContents` first, so a write cannot leave the previous entry's
    /// types sitting alongside the new one — which would make the very
    /// next capture return the wrong thing.
    func write(_ content: ClipboardContent) {
        clearContents()
        switch content {
        case .text(let string):
            setString(string, forType: .string)
        case .image(let data, let ext):
            setData(data, forType: ext == "tiff" ? .tiff : .png)
        }
    }
}
